// These constants are defined in TypeScript and substituted at runtime.
#define MAX_NUM_RING_DOTS $maxNumRingDots
#define NUM_PIPES $numPipes

// Constants duplicated TypeScript.
#define SHADING_PHONG 0
#define SHADING_DEBUG 1

#define Interval vec2

precision highp float;
uniform vec2 iResolution;

// Camera & viewer parameters.
uniform vec3 cameraPosition_; // cameraPosition_ is used by Three.js
uniform vec3 cameraDirection;
uniform vec3 cameraX;
uniform vec3 cameraY;
uniform float crossSectionW;

// Geometry parameters.
uniform vec3 pipes[NUM_PIPES];
uniform vec3 ringDots[MAX_NUM_RING_DOTS];
uniform vec3 baseColor;

// Display options.
uniform int shading;
uniform bool showRings;

const float FAR = 1e3;
const float EPSILON = 1e-4;

float square(float x) {
  return x * x;
}

float squaredLength(vec2 x) {
  return dot(x, x);
}

float squaredLength(vec3 x) {
  return dot(x, x);
}

int integerMod(int a, int b) {
  return a - b * (a / b);
}

bool Interval_empty(Interval i) {
  return i.x == FAR && i.y == FAR;
}

bool Interval_contains(Interval i, float t) {
  return i.x <= t && t <= i.y;
}

bool Interval_anti_contains(Interval i, float t) {
  return t < i.x || i.y < t;
}

struct Ray {
  vec3 origin;
  vec3 direction;
};

vec3 Ray_at(Ray ray, float t) {
  return ray.origin + t * ray.direction;
}

struct Camera {
  vec3 position;
  vec3 direction;
  float focalLength;
  vec3 x;
  vec3 y;
};

Ray Camera_ray(Camera camera, Interval position) {
  vec3 direction = normalize(
    camera.direction * camera.focalLength + (camera.x * position.x + camera.y * position.y)
  );
  return Ray(camera.position, direction);
}

struct Sphere {
  vec3 center;
  float radius;
};

vec3 Sphere_normal(Sphere sphere, vec3 x) {
  return normalize(x - sphere.center);
}

Interval intersectRaySphere(Ray ray, Sphere sphere) {
  vec3 rayOrigin = ray.origin;
  vec3 rayDirection = ray.direction;
  vec3 center = sphere.center;
  float radius = sphere.radius;
  float discriminant = (
    square(dot(rayDirection, rayOrigin - center)) -
    (squaredLength(rayOrigin - center) - square(radius))
  );
  if (discriminant < 0.0) {
    return Interval(FAR, FAR);
  }
  float tmp = -dot(rayDirection, rayOrigin - center);
  float tmp2 = sqrt(discriminant);
  float t1 = tmp - tmp2;
  float t2 = tmp + tmp2;
  return Interval(t1, t2);
}

// Axis is parallel to Z, plane is XY
struct Pipe {
  vec3 p;
  float w;
};

vec3 Pipe_normal(Pipe pipe, vec3 p) {
  float a = pipe.p.x;
  float b = pipe.p.y;
  float c = pipe.p.z;
  float w = pipe.w;
  float x = p.x;
  float y = p.y;
  float z = p.z;
  vec3 tmp = vec3(
    2.0 * a * (a * x + b * y + c * z) - 2.0 * b * (a * y - b * x + c * w),
    2.0 * a * (a * y - b * x + c * w) + 2.0 * b * (a * x + b * y + c * z),
    2.0 * c * (a * x + b * y + c * z)
  );
  vec3 normal = normalize(tmp);
  return normal;
}

Interval intersectRayPipe(Ray ray, Pipe pipe) {
  float a = pipe.p.x;
  float b = pipe.p.y;
  float c = pipe.p.z;
  float w = pipe.w;

  float x_o = ray.origin.x;
  float y_o = ray.origin.y;
  float z_o = ray.origin.z;
  float x_d = ray.direction.x;
  float y_d = ray.direction.y;
  float z_d = ray.direction.z;

  // Expressions generated by SymPy by setting:
  //     f = (a * x + b * y + c * z) ** 2 + (-b * x + a * y + c * w) ** 2 - 1
  // and then substituting (x,y,z) = (x_o,y_o,z_o) + (x_d,y_d,z_d) * t and finding the quadratic
  // f(t) = At^2 + Bt + C. f(t) = 0 are the solutions, so use quadratic formula.
  float A = a*a*x_d*x_d + a*a*y_d*y_d + 2.0*a*c*x_d*z_d + b*b*x_d*x_d + b*b*y_d*y_d + 2.0*b*c*y_d*z_d + c*c*z_d*z_d ;
  float B = 2.0*a*a*x_d*x_o + 2.0*a*a*y_d*y_o + 2.0*a*c*w*y_d + 2.0*a*c*x_d*z_o + 2.0*a*c*x_o*z_d + 2.0*b*b*x_d*x_o + 2.0*b*b*y_d*y_o - 2.0*b*c*w*x_d + 2.0*b*c*y_d*z_o + 2.0*b*c*y_o*z_d + 2.0*c*c*z_d*z_o ;
  float C = a*a*x_o*x_o + a*a*y_o*y_o + 2.0*a*c*w*y_o + 2.0*a*c*x_o*z_o + b*b*x_o*x_o + b*b*y_o*y_o - 2.0*b*c*w*x_o + 2.0*b*c*y_o*z_o + c*c*w*w + c*c*z_o*z_o - 1.0 ;

  float discriminant = B * B - 4.0 * A * C;
  if (discriminant < 0.0) {
    return Interval(FAR, FAR);
  }

  return Interval(
    (-B - sqrt(discriminant)) / (2.0 * A),
    (-B + sqrt(discriminant)) / (2.0 * A)
  );
}

Ray getCameraRay() {
  Camera camera = Camera(
    cameraPosition_, // position
    cameraDirection, // direction
    2.0, // focal length
    cameraX, // X
    cameraY // Y
  );

  // Normalized 0 to 1. Y-axis is up.
  vec2 positionUnipolar = gl_FragCoord.xy / iResolution;
  // Normalized -1 to 1 in both axes.
  vec2 positionBipolar = positionUnipolar * 2.0 - 1.0;
  float aspectRatio = iResolution.x / iResolution.y;
  // Fixed to account for aspect ratio. -1 to 1 in the shorter axis.
  vec2 position = positionBipolar * vec2(
    max(aspectRatio, 1.0),
    max(1.0 / aspectRatio, 1.0)
  );

  Ray result = Camera_ray(camera, position);
  return result;
}

float lambert(vec3 normal, vec3 light) {
  // Assume normal is normalized.
  return max(dot(normal, light), 0.0);
}

float specular(vec3 normal, vec3 light, vec3 viewer, float exponent) {
  // Light is assumed to be infinitely far away.
  vec3 reflectedNormal = 2.0 * dot(normal, light) * normal - light;
  return pow(max(dot(reflectedNormal, viewer), 0.0), exponent);
}

vec3 shadePhong(vec3 normal, vec3 viewer) {
  // Assume normal is normalized.
  vec3 light1 = normalize(vec3(3.0, 1.0, 1.0));
  vec3 light2 = normalize(vec3(-1.0, -1.0, -1.0));
  float specularExponent = 30.0;

  vec3 color = (
    baseColor * 0.2
    + lambert(normal, light1) * baseColor * 0.9
    + specular(normal, light1, viewer, specularExponent) * vec3(1.0) * 0.4
    + lambert(normal, light2) * baseColor * 0.2
    + specular(normal, light2, viewer, specularExponent) * vec3(1.0) * 0.2
  );
  return color;
}

vec3 shadeDebug(vec3 normal, vec3 viewer) {
  vec3 light = normalize(vec3(3.0, 1.0, 1.0));
  vec3 rainbowColor = vec3(0.5) + normal * 0.5;
  float intensity = max(dot(normal, light), 0.0);
  vec3 color = rainbowColor * (0.6 + intensity * 0.4);
  return color;
}

vec4 render(Ray ray) {
  float pi = radians(180.0);

  float sphereRadius = 0.04;

  // Cast a ray onto each pipe and find the intervals of intersection.
  Interval intervals[NUM_PIPES];
  for (int i = 0; i < NUM_PIPES; i++) {
    Pipe pipe = Pipe(pipes[i], crossSectionW);
    intervals[i] = intersectRayPipe(ray, pipe);
  }

  /*
  This is where we compute the Boolean operations on the intersection intervals. Formally we have N
  closed intervals bounded by 2N endpoints P, and the set S is the result of taking some Boolean
  operation on those intervals. We want to know if S is empty, and if it is not empty find
  tmin = min(S).

  It is easy to test whether a point is in S: test it against each of the intervals, and run those
  results through the Boolean ops.

  The 2N endpoints in order divide the real line into 2N + 2 segments. S is a union of those
  segments. So to fully characterize S, we can just test the 2N endpoints against S. The smallest
  endpoint in S is tmin.
  */
  float tmin = FAR;
  for (int i = 0; i < NUM_PIPES; i++) {
    // Test the min point of the interval.
    float t = intervals[i].x;
    bool p[NUM_PIPES];
    for (int j = 0; j < NUM_PIPES; j++) {
      p[j] = Interval_contains(intervals[j], t);
    }
    // This expression is generated in TypeScript.
    bool hit = $csgCode;
    if (hit) {
      tmin = min(tmin, t);
    }

    // Max point untested.
  }

  if (showRings) {
    for (int i = 0; i < MAX_NUM_RING_DOTS; i++) {
      Sphere sphere1 = Sphere(ringDots[i], sphereRadius);
      Interval intervalSphere = intersectRaySphere(ray, sphere1);
      if (intervalSphere.x <= tmin && !Interval_empty(intervalSphere)) {
        // Dots have flat shading.
        vec3 color = vec3(1.0, 1.0, 1.0);
        return vec4(color, 1.0);
      }
    }
  }

  if (tmin == FAR) {
    return vec4(0.0, 0.0, 0.0, 1.0);
  }

  // We only have the distance of intersection, not the actual pipe we hit, but we can easily
  // determine that by just looking for the pipe whose intersection interval matches that tmin.
  Pipe pipe;
  bool invert = false;
  for (int i = 0; i < NUM_PIPES; i++) {
    if (tmin == intervals[i].x || tmin == intervals[i].y) {
      pipe = Pipe(pipes[i], crossSectionW);
      if (tmin == intervals[i].y) {
        invert = true;
      }
    }
  }
  vec3 x = Ray_at(ray, tmin);
  vec3 normal = Pipe_normal(pipe, x);
  if (invert) {
    normal *= -1.0;
  }
  vec3 viewer = ray.direction * -1.0;
  vec3 color = shading == SHADING_DEBUG ?
    shadeDebug(normal, viewer)
    : shadePhong(normal, viewer);
  return vec4(color, 1.0);
}

void main() {
  gl_FragColor = render(getCameraRay());
}