import { Vec3 } from "ogl";
import { Matrix3, Vector3 } from "three";
import * as mathUtils from "./mathUtils";

/**
 * Given three interior angles of a spherical triangle, return the side length of the side opposite
 * the FIRST angle.
 */
function sphericalTriangleSide(angle1: number, angle2: number, angle3: number): number {
  return Math.acos(
    (Math.cos(angle1) + Math.cos(angle2) * Math.cos(angle3)) /
    (Math.sin(angle2) * Math.sin(angle3))
  )
}

/**
 * Given three interior angles of a spherical triangle, produce three unit vectors realizing that
 * spherical triangle on the unit sphere. The first unit vector is guaranteed to be (0, 0, 1).
 */
export function makeSphericalTriangle(angle1: number, angle2: number, angle3: number): Vec3[] {
  if (angle1 + angle2 + angle3 < Math.PI) {
    throw new Error("Invalid spherical triangle: angles must sum to 180 degrees or more");
  }
  const point1 = new Vec3(0, 0, 1);
  const side12 = sphericalTriangleSide(angle3, angle1, angle2);
  const side13 = sphericalTriangleSide(angle2, angle1, angle3);
  const point2 = mathUtils.fromSpherical(1, 0, Math.PI / 2 - side12);
  const point3 = mathUtils.fromSpherical(1, angle1, Math.PI / 2 - side13);
  return [point1, point2, point3];
}

/**
 * Given the interior angles of a spherical triangle, produce a set of three vectors which are the
 * normals of the three planes that cut the triangle.
 */
export function makeSphericalTriangleMirrors(angle1: number, angle2: number, angle3: number): Vec3[] {
  const points = makeSphericalTriangle(angle1, angle2, angle3);
  return [
    points[1].clone().cross(points[2]).normalize(),
    points[2].clone().cross(points[0]).normalize(),
    points[0].clone().cross(points[1]).normalize()
  ];
}

/**
 * Given a Coxeter word as an array of integers and an array of 3x3 matrices, multiply the matrices
 * together to produce the matrix corresponding to that word. For example, if the Coxeter word is
 * [2, 1, 0, 2] and the matrices are [M0, M1, M2], then the result will be the matrix multiplication
 * M2 M1 M0 M2.
 */
function realizeCoxeterWord(word: number[], operators: Matrix3[]): Matrix3 {
  let result = new Matrix3();
  for (let operator of word) {
    result = result.multiply(operators[operator]);
  }
  return result;
}

interface PointGroupElement {
  matrix: Matrix3,
  coxeterWord: number[],
}

function dedupePoints(points: Vector3[]): Vector3[] {
  const result: Vector3[] = [];
  for (let point of points) {
    if (!result.some((point2) => point.distanceTo(point2) <= 1e-3)) {
      result.push(point);
    }
  }
  return result;
}

export class PointGroup {
  operators: Matrix3[];
  elements: PointGroupElement[];

  constructor(operators: Matrix3[], elements: PointGroupElement[]) {
    this.operators = operators;
    this.elements = elements;
  }

  get order(): number {
    return this.elements.length;
  }

  /**
   * Given a description of a Schwarz triangle, produce the point group generated by it.
   */
  static fromSchwarzTriangle(n1: number, n2: number, n3: number): PointGroup {
    // Gather three reflection operators which generate the group, notated R1 R2 R3 in later comments.
    const mirrors = makeSphericalTriangleMirrors(Math.PI / n1, Math.PI / n2, Math.PI / n3);
    const operators: Matrix3[] = mirrors.map((mirror) =>
      mathUtils.householder(mathUtils.ogl2three(mirror))
    );
    // Stack for depth-first search is initialized with the identity operator.
    const stack: PointGroupElement[] = [
      { matrix: new Matrix3(), coxeterWord: [] }
    ];
    const elements: PointGroupElement[] = [];

    while (true) {
      const candidate = stack.pop();
      // If the stack is empty, exit.
      if (!candidate) {
        break;
      }
      // If any existing element in the point group has a matrix which is identical (with a
      // floating-point fudge factor) then ignore it.
      if (elements.some((x) => mathUtils.matrixMaxError(x.matrix, candidate.matrix) < 1e-3)) {
        continue;
      }
      // This is now officially a new element E of the point group.
      elements.push(candidate);

      if (elements.length > 120) {
        throw new Error("Maximum group order exceeded. Infinite Coxeter group?");
      }

      // For the three operators, add R1*E, R2*E, R3*E to the stack. Record their matrices and their
      // Coxeter words.
      for (let operator = 0; operator < 3; operator++) {
        const coxeterWord = [operator].concat(candidate.coxeterWord);
        const matrix = realizeCoxeterWord(coxeterWord, operators);
        stack.push({ matrix, coxeterWord });
      }
    }

    return new PointGroup(operators, elements);
  }

  orbit(point: Vector3): Vector3[] {
    let result = this.elements.map((element) =>
      point.clone().applyMatrix3(element.matrix)
    );
    result = dedupePoints(result);
    return result;
  }
}