import { Matrix3, Vector3 } from "three";
import * as mathUtils from "./mathUtils";
import { type Fraction, type FractionLike, asFraction } from "./fraction";
import { type PolytwisterSymbolLike, SchlafliSymbol } from "./symbol";

export interface Polyhedron {
  vertices: Vector3[],
  edges: [number, number][]
  faces: Face[]
}

interface Face {
  vertexIndices: number[],
  center: Vector3
}

interface Vertex {
  position: Vector3,
  matrix: Matrix3
}

function schwarzAngle(fraction: Fraction): number {
  return Math.PI / (fraction.n / fraction.d);
}

const GENERATOR_POINT = new Vector3(0, 0, 1);

/**
 * A Schwarz triangle is a spherical triangle that tiles the sphere. It is specified as (a b c)
 * where the three interior angles are pi/a pi/b pi/c.
 */
export class SchwarzTriangle {
  n1: Fraction;
  n2: Fraction;
  n3: Fraction;

  constructor(n1: FractionLike, n2: FractionLike, n3: FractionLike) {
    this.n1 = asFraction(n1);
    this.n2 = asFraction(n2);
    this.n3 = asFraction(n3);
    this.check();
  }

  get angle1() { return schwarzAngle(this.n1); }
  get angle2() { return schwarzAngle(this.n2); }
  get angle3() { return schwarzAngle(this.n3); }

  static fromSymbol(symbol: PolytwisterSymbolLike) {
    const symbol2 = SchlafliSymbol.from(symbol);
    return new SchwarzTriangle(symbol2.ringFigure, symbol2.twister, 2);
  }

  private check() {
    if (this.angle1 + this.angle2 + this.angle3 <= Math.PI) {
      throw new Error("Invalid spherical triangle: angles must sum to more than 180 degrees");
    }
  }

  /**
   * Given three interior angles of a spherical triangle, return the side length of the side opposite
   * the FIRST angle.
   */
  static sphericalTriangleSide(angle1: number, angle2: number, angle3: number): number {
    return Math.acos(
      (Math.cos(angle1) + Math.cos(angle2) * Math.cos(angle3)) /
      (Math.sin(angle2) * Math.sin(angle3))
    );
  }

  /**
   * Given three interior angles of a spherical triangle, produce three unit vectors realizing that
   * spherical triangle on the unit sphere. The first unit vector is guaranteed to be (0, 0, 1).
   */
  vertices(): Vector3[] {
    const point1 = new Vector3(0, 0, 1);
    const side12 = SchwarzTriangle.sphericalTriangleSide(this.angle3, this.angle1, this.angle2);
    const side13 = SchwarzTriangle.sphericalTriangleSide(this.angle2, this.angle1, this.angle3);
    const point2 = mathUtils.fromSpherical(1, 0, Math.PI / 2 - side12);
    const point3 = mathUtils.fromSpherical(1, this.angle1, Math.PI / 2 - side13);
    const result = [point1, point2, point3];
    return result;
  }

  /**
   * Produce a set of three vectors which are the normals of the three planes that cut the triangle.
   */
  mirrors(): Vector3[] {
    const points = this.vertices();
    return [
      points[1].clone().cross(points[2]).normalize(),
      points[2].clone().cross(points[0]).normalize(),
      points[0].clone().cross(points[1]).normalize()
    ];
  }

}

/**
 * Given a Coxeter word as an array of integers and an array of 3x3 matrices, multiply the matrices
 * together to produce the matrix corresponding to that word. For example, if the Coxeter word is
 * [2, 1, 0, 2] and the matrices are [M0, M1, M2], then the result will be the matrix multiplication
 * M2 M1 M0 M2.
 */
function realizeCoxeterWord(word: number[], operators: Matrix3[]): Matrix3 {
  let result = new Matrix3();
  for (let operator of word) {
    result = result.multiply(operators[operator]);
  }
  return result;
}

interface PointGroupElement {
  matrix: Matrix3,
  coxeterWord: number[],
}

function dedupePoints(points: Vector3[]): Vector3[] {
  const result: Vector3[] = [];
  for (let point of points) {
    if (!result.some((point2) => point.distanceTo(point2) <= 1e-3)) {
      result.push(point);
    }
  }
  return result;
}

/**
 * A point group is a finite collection of 3x3 orthogonal matrices with the property that the
 * product of any two matrices, or the inverse of any one matrix, is also in the group. In this
 * software point groups are produced algorithmically and generated from a set of three mirrors, and
 * all point groups are achiral.
 */
export class PointGroup {
  // The operators are three reflection matrices that generate the group. The first two operators
  // are guaranteed to leave GENERATOR_POINT (0, 0, 1) invariant, while the third one is not.
  operators: Matrix3[];
  elements: PointGroupElement[];
  schwarzTriangle: SchwarzTriangle;

  constructor(schwarzTriangle: SchwarzTriangle, operators: Matrix3[], elements: PointGroupElement[]) {
    this.operators = operators;
    this.elements = elements;
    this.schwarzTriangle = schwarzTriangle;
  }

  get order(): number {
    return this.elements.length;
  }

  /**
   * Given a description of a Schwarz triangle, produce the point group generated by it.
   */
  static fromSchwarzTriangle(schwarzTriangle: SchwarzTriangle): PointGroup {
    // Gather three reflection operators which generate the group, notated R1 R2 R3 in later comments.
    const mirrors = schwarzTriangle.mirrors();
    const operators: Matrix3[] = mirrors.map((mirror) =>
      mathUtils.householder(mirror)
    );
    // Stack for depth-first search is initialized with the identity operator.
    const stack: PointGroupElement[] = [
      { matrix: new Matrix3(), coxeterWord: [] }
    ];
    const elements: PointGroupElement[] = [];

    while (true) {
      const candidate = stack.pop();
      // If the stack is empty, exit.
      if (!candidate) {
        break;
      }
      // If any existing element in the point group has a matrix which is identical (with a
      // floating-point fudge factor) then ignore it.
      if (elements.some((x) => mathUtils.matrixMaxError(x.matrix, candidate.matrix) < 1e-3)) {
        continue;
      }
      // This is now officially a new element E of the point group.
      elements.push(candidate);

      if (elements.length > 120) {
        throw new Error("Maximum group order exceeded. Infinite Coxeter group?");
      }

      // For the three operators, add R1*E, R2*E, R3*E to the stack. Record their matrices and their
      // Coxeter words.
      for (let operator = 0; operator < 3; operator++) {
        const coxeterWord = [operator].concat(candidate.coxeterWord);
        const matrix = realizeCoxeterWord(coxeterWord, operators);
        stack.push({ matrix, coxeterWord });
      }
    }

    return new PointGroup(schwarzTriangle, operators, elements);
  }

  orbit(): Vector3[] {
    let result = this.elements.map((element) =>
      GENERATOR_POINT.clone().applyMatrix3(element.matrix)
    );
    result = dedupePoints(result);
    return result;
  }

  makePolyhedron(): Polyhedron {
    // Apply all elements in the group to the vertex, keeping track of the matrices used to produce
    // them.
    let vertexCandidates = this.elements.map((element) =>
      ({
        position: GENERATOR_POINT.clone().applyMatrix3(element.matrix),
        matrix: element.matrix
      })
    );

    // Deduplicate the vertices.
    const vertices: Vertex[] = [];
    for (let vertex of vertexCandidates) {
      if (!vertices.some((vertex2) => vertex.position.distanceTo(vertex2.position) <= 1e-3)) {
        vertices.push(vertex);
      }
    }

    let edges: [number, number][] = [];

    // To produce edges, we take advantage of the following facts:
    // 1. If p is the generator point, then R1*p is an adjacent vertex. (R2 p = R3 p = p, so there's
    // no need to check those; consequently the polyhedron is edge-transitive.) So
    // [p, R1*p] gives us an edge.
    // 2. All other edges are formed by taking all elements of the group and transforming that edge.
    for (let element of this.elements) {
      const vertex1 = GENERATOR_POINT.clone().applyMatrix3(element.matrix);
      const vertex2 = GENERATOR_POINT.clone().applyMatrix3(this.operators[0]).applyMatrix3(element.matrix);
      const i = findVertex(vertex1, vertices);
      const j = findVertex(vertex2, vertices);
      if (i === null || j === null) {
        throw new Error("Can't find edge ending")
      }
      edges.push([i, j]);
    }
    edges = dedupeEdges(edges);

    /**
     * Given an "edge walker" matrix and a number of edges, produce a face object.
     * An edge walker is a matrix M that, given any vertex v, Mv is an adjacent
     * vertex. Thus v, Mv, M^2 v, M^3 v, etc. produces all vertices of the face.
     */
    function makeFace(edgeWalker: Matrix3, count: number, center: Vector3): Face {
      let vertex = GENERATOR_POINT;
      let face = [];
      for (let i = 0; i < count; i++) {
        vertex = vertex.clone().applyMatrix3(edgeWalker);
        const vertexIndex = findVertex(vertex, vertices);
        if (vertexIndex === null) {
          throw new Error("Vertex not found");
        }
        face.push(vertexIndex);
      }
      return {
        vertexIndices: face,
        center
      };
    }
  
    /**
     * Given a Face, produce all possible transformations of it using the point
     * group. The results are not deduplicated.
     */
    function symmetrizeFace(face: Face, elements: Matrix3[]): Face[] {
      const vertexLocations = face.vertexIndices.map((x) => vertices[x].position);
      const result = [];
      for (let element of elements) {
        const vertexLocations2 = vertexLocations.map((x) => x.clone().applyMatrix3(element));
        const vertexIndices = vertexLocations2.map((x) => {
          let result = findVertex(x, vertices);
          if (result === null) {
            throw new Error("Vertex not found");
          }
          return result;
        });
        const center = face.center.clone().applyMatrix3(element);
        result.push({ vertexIndices, center });
      }
      return result;
    }

    const elementMatrices = this.elements.map((x) => x.matrix);

    const schwarzTriangleVertices = this.schwarzTriangle.vertices();

    let face1 = makeFace(
      realizeCoxeterWord([0, 1], this.operators),
      this.schwarzTriangle.n3.n,
      schwarzTriangleVertices[2],
    );
    let face2 = makeFace(
      realizeCoxeterWord([0, 2], this.operators),
      this.schwarzTriangle.n2.n,
      schwarzTriangleVertices[1],
    );
    let faces: Face[] = [];
    faces = faces.concat(symmetrizeFace(face1, elementMatrices));
    faces = faces.concat(symmetrizeFace(face2, elementMatrices));
    // faces = faces.filter((x) => x.vertexIndices.length > 2);
    faces = dedupeFaces(faces);

    return {
      vertices: vertices.map((x) => x.position),
      edges,
      faces
    };
  }
}

function findVertex(point: Vector3, vertices: Vertex[]): number | null {
  for (let [i, candidate] of vertices.entries()) {
    if (candidate.position.distanceTo(point) <= 1e-3) {
      return i;
    }
  }
  return null;
}

function dedupeEdges(edges: [number, number][]): [number, number][] {
  const result: [number, number][] = [];
  for (let edge of edges) {
    let found = false;
    for (let edge2 of result) {
      if (edge[0] === edge2[0] && edge[1] === edge2[1]) {
        found = true;
        break;
      }
      if (edge[0] === edge2[1] && edge[1] === edge2[0]) {
        found = true;
        break;
      }
    }
    if (found === false) {
      result.push(edge);
    }
  }
  return result;
}

function facesEqual(face1: Face, face2: Face): boolean {
  return face1.center.distanceTo(face2.center) <= 1e-3;
}

function dedupeFaces(faces: Face[]): Face[] {
  const result: Face[] = [];
  for (let face of faces) {
    if (!result.some((candidate) => facesEqual(face, candidate))) {
      result.push(face);
    }
  }
  return result;
}

export function symbolToPolyhedron(symbol: SchlafliSymbol): Polyhedron {
  return PointGroup.fromSchwarzTriangle(
    SchwarzTriangle.fromSymbol(symbol)
  ).makePolyhedron();
}