import { Matrix3, Vector3 } from "three";
import * as _ from "lodash";
import * as mathUtils from "./mathUtils";
import {
  type Fraction,
  type FractionLike,
  asFraction,
  fractionToString,
} from "./fraction";
import { type PolytwisterSymbolLike, PolytwisterSymbol } from "./symbol";

export class Polyhedron {
  vertices: Vertex[];
  edges: Edge[];
  faces: Face[];

  constructor(vertices: Vertex[], edges: Edge[], faces: Face[]) {
    this.vertices = vertices;
    this.edges = edges;
    this.faces = faces;
  }

  /**
   * Return the array [num vertices, num edges, num faces].
   */
  faceVector(): [number, number, number] {
    return [this.vertices.length, this.edges.length, this.faces.length];
  }

  vertexPositions(): Vector3[] {
    return this.vertices.map((v) => v.position);
  }

  getAdjacentFaceIndices(faceIndex: number): number[] {
    const adjacentFaces: number[] = [];
    this.faces[faceIndex].edges.forEach((edgeIndex) => {
      for (let [faceIndex2, face] of this.faces.entries()) {
        if (face.edges.indexOf(edgeIndex) !== -1 && faceIndex2 !== faceIndex) {
          adjacentFaces.push(faceIndex2);
        }
      }
    });
    return adjacentFaces;
  }

  /**
   * Find a single face in the given orbit. Returns -1 if none are found.
   */
  getFaceIndexFromOrbit(orbit: number): number {
    return this.faces.findIndex((face) => face.orbit === orbit);
  }
}

interface Face {
  // These are the indices of vertices, not their locations. (vertexIndices felt too long.)
  vertices: number[];
  // These are the indices of edges, not their locations. (edgeIndices felt too long.)
  edges: number[];
  // Identifies which type of face as distinguished by the symmetry group. This
  // is 0 or 1 for quasiregulars, and always 0 for regulars.
  orbit: number;
  center: Vector3;
  symbol: Fraction;
}

interface Edge {
  vertex1: number;
  vertex2: number;
  // The "position" of the edge doesn't really have much geometrical meaning, but it must respect
  // the symmetry of the polyhedron generated by the Wythoffian construction. This allows us to
  // distinguish different edges in digonal faces -- it is not sufficient to test edge equality
  // using endpoints.
  position: Vector3;
}

interface Vertex {
  position: Vector3;
}

interface PointAndMatrix {
  matrix: Matrix3;
  position: Vector3;
}

const EPSILON = 1e-3;

function verticesEqual(a: Vertex, b: Vertex): boolean {
  return a.position.distanceTo(b.position) <= EPSILON;
}

function findVertex(vertices: Vertex[], position: Vector3): number {
  const result = _.findIndex(
    vertices,
    (vertex) => vertex.position.distanceTo(position) <= EPSILON,
  );
  if (result === -1) {
    throw new Error("Couldn't find vertex");
  }
  return result;
}

function findEdge(edges: Edge[], position: Vector3): number {
  const result = _.findIndex(
    edges,
    (edge) => edge.position.distanceTo(position) <= EPSILON,
  );
  if (result === -1) {
    throw new Error("Couldn't find edge");
  }
  return result;
}

function schwarzAngle(fraction: Fraction): number {
  return Math.PI / (fraction.n / fraction.d);
}

function isNearInteger(n: number): boolean {
  return Math.abs(n - Math.round(n)) <= EPSILON;
}

const GENERATOR_POINT = new Vector3(0, 0, 1);

/**
 * A Schwarz triangle is a spherical triangle that tiles the sphere. It is specified as (a b c)
 * where the three interior angles are pi/a pi/b pi/c.
 */
export class SchwarzTriangle {
  n1: Fraction;
  n2: Fraction;
  n3: Fraction;

  constructor(n1: FractionLike, n2: FractionLike, n3: FractionLike) {
    this.n1 = asFraction(n1);
    this.n2 = asFraction(n2);
    this.n3 = asFraction(n3);
    this.check();
  }

  get angle1() {
    return schwarzAngle(this.n1);
  }
  get angle2() {
    return schwarzAngle(this.n2);
  }
  get angle3() {
    return schwarzAngle(this.n3);
  }

  static fromSymbol(symbol: PolytwisterSymbolLike) {
    const symbol2 = PolytwisterSymbol.from(symbol);
    return new SchwarzTriangle(
      symbol2.ring,
      symbol2.twister1,
      symbol2.twister2,
    );
  }

  asString() {
    return `(${fractionToString(this.n1)} ${fractionToString(this.n2)} ${fractionToString(this.n3)})`;
  }

  private check() {
    if (this.angle1 + this.angle2 + this.angle3 <= Math.PI) {
      throw new Error(
        `Invalid spherical triangle ${this.asString()}: angles must sum to more than 180 degrees`,
      );
    }
  }

  /**
   * Given three interior angles of a spherical triangle, return the side length of the side opposite
   * the FIRST angle.
   */
  static sphericalTriangleSide(
    angle1: number,
    angle2: number,
    angle3: number,
  ): number {
    return Math.acos(
      (Math.cos(angle1) + Math.cos(angle2) * Math.cos(angle3)) /
        (Math.sin(angle2) * Math.sin(angle3)),
    );
  }

  /**
   * Given three interior angles of a spherical triangle, produce three unit vectors realizing that
   * spherical triangle on the unit sphere. The first unit vector is guaranteed to be (0, 0, 1),
   * and the second is guaranteed to be of the form (x, 0, z).
   */
  vertices(): Vector3[] {
    const point1 = new Vector3(0, 0, 1);
    const side12 = SchwarzTriangle.sphericalTriangleSide(
      this.angle3,
      this.angle1,
      this.angle2,
    );
    const side13 = SchwarzTriangle.sphericalTriangleSide(
      this.angle2,
      this.angle1,
      this.angle3,
    );
    const point2 = mathUtils.fromSpherical(1, 0, Math.PI / 2 - side12);
    const point3 = mathUtils.fromSpherical(
      1,
      this.angle1,
      Math.PI / 2 - side13,
    );
    const result = [point1, point2, point3];
    return result;
  }

  /**
   * Produce a set of three vectors which are the normals of the three planes that cut the triangle.
   */
  mirrors(): Vector3[] {
    const points = this.vertices();
    return [
      points[1].clone().cross(points[2]).normalize(),
      points[2].clone().cross(points[0]).normalize(),
      points[0].clone().cross(points[1]).normalize(),
    ];
  }

  static mobiusFromPoints(p2: Vector3, p3: Vector3): SchwarzTriangle {
    if (Math.abs(p2.y) > EPSILON) {
      throw new Error("Y-coordinate of p2 must be 0");
    }
    const p1 = GENERATOR_POINT;
    const angle1 = mathUtils.reject(p2, p1).angleTo(mathUtils.reject(p3, p1));
    const angle2 = mathUtils.reject(p3, p2).angleTo(mathUtils.reject(p1, p2));
    const angle3 = mathUtils.reject(p1, p3).angleTo(mathUtils.reject(p2, p3));
    const n1 = Math.round(Math.PI / angle1);
    const n2 = Math.round(Math.PI / angle2);
    const n3 = Math.round(Math.PI / angle3);
    return new SchwarzTriangle(n1, n2, n3);
  }

  /**
   * Find a Mobius triangle which is a fundamental triangle of this one.
   */
  fundamentalMobiusTriangle(): Vector3[] {
    const mirrors = this.mirrors();
    const group = SymmetryGroup.fromSchwarzTriangle(this);
    let allMirrors = [
      ...group.orbit(mirrors[0]),
      ...group.orbit(mirrors[1]),
      ...group.orbit(mirrors[2]),
    ];
    allMirrors = dedupeMirrors(allMirrors);

    // Pick one mirror.
    let mirror1 = allMirrors[0];

    // Find a mirror that has the smallest nonzero angle with the first mirror. The possible Mobius
    // triangles are (p 2 2) (3 3 2) (4 3 2) (5 3 2). This angle corresponds to the first number in
    // the Mobius triangle.
    let leastAngle = Infinity;
    let mirror2 = null;
    for (let i = 0; i < allMirrors.length; i++) {
      const candidate = allMirrors[i];
      const angle = candidate.angleTo(mirror1);
      if (angle > EPSILON && angle < leastAngle) {
        mirror2 = candidate;
        leastAngle = angle;
      }
    }
    if (mirror2 === null) {
      throw new Error("Shouldn't happen");
    }

    for (let i = 0; i < allMirrors.length; i++) {
      const candidate = allMirrors[i];
      const angle13 = candidate.angleTo(mirror1);
      const angle12 = candidate.angleTo(mirror2);
      if (
        angle12 > EPSILON &&
        angle13 > EPSILON &&
        isNearInteger(Math.PI / angle13) &&
        isNearInteger(Math.PI / angle12) &&
        (Math.round(Math.PI / angle12) === 2 ||
          Math.round(Math.PI / angle13) === 2)
      ) {
        return [mirror1, mirror2, candidate];
      }
    }

    throw new Error("Shouldn't happen");
  }
}

/**
 * Given a Coxeter word as an array of integers and an array of 3x3 matrices, multiply the matrices
 * together to produce the matrix corresponding to that word. For example, if the Coxeter word is
 * [2, 1, 0, 2] and the matrices are [M0, M1, M2], then the result will be the matrix multiplication
 * M2 M1 M0 M2.
 */
function realizeCoxeterWord(word: number[], operators: Matrix3[]): Matrix3 {
  let result = new Matrix3();
  for (let operator of word) {
    result = result.multiply(operators[operator]);
  }
  return result;
}

interface Symmetry {
  matrix: Matrix3;
  coxeterWord: number[];
}

function dedupePoints(points: Vector3[]): Vector3[] {
  return _.uniqWith(
    points,
    (point1, point2) => point1.distanceTo(point2) <= EPSILON,
  );
}

function dedupeMirrors(mirrors: Vector3[]): Vector3[] {
  const result: Vector3[] = [];
  for (let mirror of mirrors) {
    if (!result.some((mirror2) => mirror.dot(mirror2) >= 1 - EPSILON)) {
      result.push(mirror);
    }
  }
  return result;
}

/**
 * A representation of a finite subgroup of O(3). "Representation" is in the formal, group-theoretic
 * sense, i.e. a set of 3x3 orthogonal matrices ("symmetries") with the following properties:
 *
 * 1. The identity matrix I is included.
 * 2. If matrices A and B are symmetries, AB is also a symmetry.
 * 3. If A is a symmetry, A^-1 is also a symmetry.
 *
 * In this software point groups are produced algorithmically and generated from a set of three
 * mirrors, and all point groups are achiral.
 */
export class SymmetryGroup {
  // The operators are three reflection matrices that generate the group. The first two operators
  // are guaranteed to leave GENERATOR_POINT (0, 0, 1) invariant, while the third one is not.
  operators: Matrix3[];
  symmetries: Symmetry[];
  schwarzTriangle: SchwarzTriangle;

  constructor(
    schwarzTriangle: SchwarzTriangle,
    operators: Matrix3[],
    symmetries: Symmetry[],
  ) {
    this.operators = operators;
    this.symmetries = symmetries;
    this.schwarzTriangle = schwarzTriangle;
  }

  get order(): number {
    return this.symmetries.length;
  }

  /**
   * Given a description of a Schwarz triangle, produce the symmetry group generated by placing
   * three mirrors at its edges.
   */
  static fromSchwarzTriangle(schwarzTriangle: SchwarzTriangle): SymmetryGroup {
    // Gather three reflection operators which generate the group, notated R1 R2 R3 in later
    // comments.
    const mirrors = schwarzTriangle.mirrors();
    const operators: Matrix3[] = mirrors.map((mirror) =>
      mathUtils.householder(mirror),
    );
    // Stack for depth-first search is initialized with the identity operator.
    const stack: Symmetry[] = [{ matrix: new Matrix3(), coxeterWord: [] }];
    const elements: Symmetry[] = [];

    while (true) {
      const candidate = stack.pop();
      // If the stack is empty, exit.
      if (!candidate) {
        break;
      }
      // If any existing element in the point group has a matrix which is identical (with a
      // floating-point fudge factor) then ignore it.
      if (
        elements.some(
          (x) => mathUtils.matrixMaxError(x.matrix, candidate.matrix) < 1e-3,
        )
      ) {
        continue;
      }
      // This is now officially a new element E of the point group.
      elements.push(candidate);

      if (elements.length > 120) {
        throw new Error(
          "Maximum group order exceeded. Infinite Coxeter group?",
        );
      }

      // For the three operators, add R1*E, R2*E, R3*E to the stack. Record their matrices and their
      // Coxeter words.
      for (let operator = 0; operator < 3; operator++) {
        const coxeterWord = [operator].concat(candidate.coxeterWord);
        const matrix = realizeCoxeterWord(coxeterWord, operators);
        stack.push({ matrix, coxeterWord });
      }
    }

    return new SymmetryGroup(schwarzTriangle, operators, elements);
  }

  orbit(point: Vector3): Vector3[] {
    let result = this.symmetries.map((element) =>
      point.clone().applyMatrix3(element.matrix),
    );
    result = dedupePoints(result);
    return result;
  }

  orbitWithMatrices(point: Vector3): PointAndMatrix[] {
    let result: PointAndMatrix[] = this.symmetries.map((element) => ({
      position: point.clone().applyMatrix3(element.matrix),
      matrix: element.matrix,
    }));
    result = _.uniqWith(
      result,
      (x1, x2) => x1.position.distanceTo(x2.position) <= EPSILON,
    );
    return result;
  }

  makePolyhedron(quasiregular: boolean): Polyhedron {
    const schwarzTriangleVertices = this.schwarzTriangle.vertices();

    // Apply all elements in the group to the vertex, keeping track of the matrices used to produce
    // them.
    const verticesTmp: Vertex[] = this.symmetries.map((element) => ({
      position: GENERATOR_POINT.clone().applyMatrix3(element.matrix),
    }));
    const vertices = _.uniqWith(verticesTmp, verticesEqual);

    // Each edge is assigned a "position." This is not actually the geometrical position, just a way
    // of distinguishing edges in a way that makes sense with the symmetry group. We can't
    // distinguish edges just by their endpoints, as that fails with digons.
    //
    // In the regular case, the edge's position is vertex 2 (and the face's center is vertex 3).
    // In the quasiregular case, the "position" is a point in the interior of the edge of the
    // Schwarz triangle opposite vertex 1 (the generator point).
    //
    // I originally used the halfway point between the two vertices, but this caused problems for
    // polyhedra like the dodecadodecahedron. The exact cause of the problems I don't fully
    // understand, but it resulted in unwanted merging of edges. Changing from 0.5 to 0.3
    // fixed this bug.
    const baseEdgePosition = quasiregular
      ? schwarzTriangleVertices[1].clone().lerp(schwarzTriangleVertices[2], 0.3)
      : schwarzTriangleVertices[1];
    const baseEdgeEndpoint1 = GENERATOR_POINT.clone();
    const baseEdgeEndpoint2 = GENERATOR_POINT.clone().applyMatrix3(
      this.operators[0],
    );

    // Take the orbit of the base edge position, deduplicating any edges in the same place, and
    // recording the (non-unique) matrix associated with the edge. Apply that transformation to the
    // base edge's endpoints to produce the new edge's endpoint locations. Then search for those
    // locations to find their indices.
    let edges: Edge[] = this.orbitWithMatrices(baseEdgePosition).map(
      (pm: PointAndMatrix) => {
        const vertex1Position = baseEdgeEndpoint1
          .clone()
          .applyMatrix3(pm.matrix);
        const vertex2Position = baseEdgeEndpoint2
          .clone()
          .applyMatrix3(pm.matrix);
        const vertex1 = findVertex(vertices, vertex1Position);
        const vertex2 = findVertex(vertices, vertex2Position);
        return { vertex1, vertex2, position: pm.position };
      },
    );

    const that = this;

    /**
     * Produce all faces of a certain type given the following:
     * 1. The center of the base face.
     * 2. A "corner rotation" matrix. This is a rotation matrix that sends one vertex of the face to
     * an adjacent vertex.
     * 3. The number of sides.
     */
    function makeFaces(
      center: Vector3,
      cornerRotation: Matrix3,
      symbol: Fraction,
      faceType: number,
    ): Face[] {
      const numSides = symbol.n;
      // Compute the vertex & edge positions of all the face's vertices by repeatedly applying the
      // corner rotation matrix.
      let vertexPosition = GENERATOR_POINT.clone();
      let edgePosition = baseEdgePosition.clone();
      let baseVertexPositions: Vector3[] = [];
      let baseEdgePositions: Vector3[] = [];
      _.range(numSides).forEach(() => {
        vertexPosition = vertexPosition.clone().applyMatrix3(cornerRotation);
        edgePosition = edgePosition.clone().applyMatrix3(cornerRotation);
        baseVertexPositions.push(vertexPosition);
        baseEdgePositions.push(edgePosition);
      });

      // Take the orbit of the center of the face, recording the (non-unique) matrix that sends the
      // base face to the face with that center. Transform the base face's vertex and edge
      // positions using the matrix, then match the edge and vertex locations.
      return that.orbitWithMatrices(center).map((pm: PointAndMatrix) => {
        const vertexPositions = baseVertexPositions.map((p) =>
          p.clone().applyMatrix3(pm.matrix),
        );
        const edgePositions = baseEdgePositions.map((p) =>
          p.clone().applyMatrix3(pm.matrix),
        );
        return {
          vertices: vertexPositions.map((p) => findVertex(vertices, p)),
          edges: edgePositions.map((p) => findEdge(edges, p)),
          center: pm.position,
          symbol,
          orbit: faceType,
        };
      });
    }

    // In the regular case, vertex 3 is the center of the face, R2*R1 is the corner rotation, and
    // the numerator of the vertex 3 angle is the number of vertices.
    const facesA = makeFaces(
      schwarzTriangleVertices[2],
      realizeCoxeterWord([0, 1], this.operators),
      this.schwarzTriangle.n3,
      0,
    );
    let faces = facesA;

    // In the quasiregular case, we have a second type of face: vertex 2 is the center of the face,
    // R3*R1 is the corner rotation, and the numerator of the vertex 2 angle is the number of
    // vertices.
    if (quasiregular) {
      const facesB = makeFaces(
        schwarzTriangleVertices[1],
        realizeCoxeterWord([0, 2], this.operators),
        this.schwarzTriangle.n2,
        1,
      );
      faces = facesA.concat(facesB);
    }

    return new Polyhedron(vertices, edges, faces);
  }
}

export function symbolToPolyhedron(symbol: PolytwisterSymbol): Polyhedron {
  return SymmetryGroup.fromSchwarzTriangle(
    SchwarzTriangle.fromSymbol(symbol),
  ).makePolyhedron(symbol.quasiregular);
}
